/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import javax.swing.JOptionPane;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
/**
 *
 * @author Faiz
 */
public class prak2 extends javax.swing.JFrame {
    
    double hargaRoti,hargaTopping;
    int BanyakPesanan=1;
    /**
     * Creates new form prak2
     */
    public prak2() { 
        initComponents();
        this.setLocationRelativeTo(null);
        
        rcash.addKeyListener(new KeyAdapter() {
            public void keyReleased(KeyEvent e) {
                bayar();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Roti = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        Topping = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        tawar = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        bakar = new javax.swing.JRadioButton();
        manis = new javax.swing.JRadioButton();
        bantal = new javax.swing.JRadioButton();
        pisang = new javax.swing.JRadioButton();
        goreng = new javax.swing.JRadioButton();
        donat = new javax.swing.JRadioButton();
        croi = new javax.swing.JRadioButton();
        brio = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        coklat = new javax.swing.JRadioButton();
        stroberi = new javax.swing.JRadioButton();
        keju = new javax.swing.JRadioButton();
        kacang = new javax.swing.JRadioButton();
        tanpa = new javax.swing.JRadioButton();
        rhitung = new javax.swing.JPanel();
        jumlah = new javax.swing.JTextField();
        btnk = new javax.swing.JButton();
        tambah = new javax.swing.JButton();
        btnh = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        rhasil = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        rcash = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        rback = new javax.swing.JTextField();
        rreset = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        bluberi = new javax.swing.JRadioButton();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Harlow Solid Italic", 0, 24)); // NOI18N
        jLabel1.setText("Roti Mas Rusydi ");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/download.jpg"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Monotype Corsiva", 1, 14)); // NOI18N
        jLabel3.setText("Di jamin Enak");

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 49, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(jLabel2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(jLabel2))))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        Roti.add(tawar);
        tawar.setText("Roti Tawar 5000");
        tawar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tawarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Kristen ITC", 0, 12)); // NOI18N
        jLabel4.setText("Silahkan Pilih Jenis Roti : ");

        Roti.add(bakar);
        bakar.setText("Roti Bakar 6000");

        Roti.add(manis);
        manis.setText("Roti Manis 7000");

        Roti.add(bantal);
        bantal.setText(" Roti Bantal  4000");

        Roti.add(pisang);
        pisang.setText("Roti Pisang 3000");

        Roti.add(goreng);
        goreng.setText("Roti Goreng 5000");

        Roti.add(donat);
        donat.setText("Donat 6000");

        Roti.add(croi);
        croi.setText("Croissant 8000");
        croi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                croiActionPerformed(evt);
            }
        });

        Roti.add(brio);
        brio.setText("Brioche 8000");

        jLabel5.setFont(new java.awt.Font("Kristen ITC", 0, 12)); // NOI18N
        jLabel5.setText("Silahkan Pilih Topping : ");

        Topping.add(coklat);
        coklat.setText("Coklat 1000");
        coklat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coklatActionPerformed(evt);
            }
        });

        Topping.add(stroberi);
        stroberi.setText("Selai Stroberi 2000");

        Topping.add(keju);
        keju.setText("Keju 3000");
        keju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kejuActionPerformed(evt);
            }
        });

        Topping.add(kacang);
        kacang.setText("Kacang 2000");

        Topping.add(tanpa);
        tanpa.setText("Tanpa Topping Gratis");

        rhitung.setBackground(new java.awt.Color(255, 255, 255));

        jumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahActionPerformed(evt);
            }
        });

        btnk.setText("-");
        btnk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkActionPerformed(evt);
            }
        });

        tambah.setText("+");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });

        btnh.setText("Hitung");
        btnh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel6.setText("Total :");

        rhasil.setEditable(false);
        rhasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rhasilActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel7.setText("Cash           :");

        rcash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rcashActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel8.setText("Kembalian : ");

        rback.setEditable(false);

        rreset.setText("Reset");
        rreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rresetActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 29, Short.MAX_VALUE)
        );

        jLabel10.setFont(new java.awt.Font("Bahnschrift", 0, 10)); // NOI18N
        jLabel10.setText("Diskon 5% untuk pembelian di atas 100k");

        javax.swing.GroupLayout rhitungLayout = new javax.swing.GroupLayout(rhitung);
        rhitung.setLayout(rhitungLayout);
        rhitungLayout.setHorizontalGroup(
            rhitungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(rhitungLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(rhitungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(rhitungLayout.createSequentialGroup()
                        .addGroup(rhitungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(rhitungLayout.createSequentialGroup()
                                .addComponent(tambah)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnk)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnh, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(rhitungLayout.createSequentialGroup()
                                .addGroup(rhitungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(rhitungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(rhitungLayout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(rcash, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(rhitungLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rback)))))
                        .addGap(31, 31, 31)
                        .addGroup(rhitungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(rhitungLayout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rhasil, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(rhitungLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(rreset, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        rhitungLayout.setVerticalGroup(
            rhitungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rhitungLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(rhitungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(rhitungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnh)
                        .addComponent(jLabel6)
                        .addComponent(rhasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tambah, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jumlah, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(rhitungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rhitungLayout.createSequentialGroup()
                        .addGroup(rhitungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(rcash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(rhitungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(rback, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rhitungLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(rreset)
                        .addGap(39, 39, 39)))
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Topping.add(bluberi);
        bluberi.setText("Selai Bluberry 2000");
        bluberi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bluberiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(252, 252, 252))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tawar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(bakar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(manis))
                                    .addGap(30, 30, 30)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(bantal, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                                        .addComponent(pisang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(goreng)))
                                .addComponent(coklat, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(stroberi)
                                .addComponent(bluberi))
                            .addGap(26, 26, 26)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tanpa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(kacang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(keju, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(donat, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(brio, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(croi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(118, Short.MAX_VALUE))
            .addComponent(rhitung, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel4)
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tawar)
                    .addComponent(bantal)
                    .addComponent(donat))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bakar)
                    .addComponent(pisang)
                    .addComponent(croi))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manis)
                    .addComponent(goreng)
                    .addComponent(brio))
                .addGap(37, 37, 37)
                .addComponent(jLabel5)
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(coklat)
                    .addComponent(keju))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stroberi)
                    .addComponent(kacang))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tanpa)
                    .addComponent(bluberi))
                .addGap(53, 53, 53)
                .addComponent(rhitung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bayar() {
    try {
        if (rcash.getText().isEmpty()) {
            rback.setText("Masukkan jumlah uang terlebih dahulu!");
            return;
        }
        int Cash = Integer.parseInt(rcash.getText());
        int Total = Integer.parseInt(rhasil.getText().replace("Rp ", "").replace(",", "")); 
        int kembalian = Cash - Total;

        if (Cash < Total) {
            rback.setText("Uang Anda Kurang");
         
        } else {
            rback.setText(String.format("Rp. %,d", kembalian)); 
        }
    } catch (NumberFormatException e) {
        rback.setText("Inputan tidak valid, masukkan angka yang benar.");
    }
}

    private void tawarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tawarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tawarActionPerformed

    private void jumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlahActionPerformed

    private void btnhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhActionPerformed
        // TODO add your handling code here:
        if (!tawar.isSelected() && !bantal.isSelected() && !donat.isSelected() && !bakar.isSelected() && !pisang.isSelected() && !goreng.isSelected() &&
        !croi.isSelected() && !brio.isSelected() && !manis.isSelected()) {
        JOptionPane.showMessageDialog(this, "Silakan pilih jenis roti terlebih dahulu!");
        return;
        }
        
        if (!coklat.isSelected() && !stroberi.isSelected() && !bluberi.isSelected() && !keju.isSelected() && !kacang.isSelected() && !tanpa.isSelected()) {
        JOptionPane.showMessageDialog(this, "Silakan pilih topping terlebih dahulu!");
        return;
        }
        int isi = Integer.parseInt(jumlah.getText());
        
        if(tawar.isSelected()){
            hargaRoti = 5000;
        }else if(bantal.isSelected()){
            hargaRoti = 4000;
        }else if(donat.isSelected()){
            hargaRoti = 6000;
        }else if(bakar.isSelected()){
            hargaRoti = 6000;
        }else if(pisang.isSelected()){
            hargaRoti = 3000;
        }else if(goreng.isSelected()){
            hargaRoti = 5000;
        }else if(croi.isSelected()){
            hargaRoti = 8000;
        }else if(brio.isSelected()){
            hargaRoti = 8000;
        }else if(manis.isSelected()){
            hargaRoti = 7000;
        }
        
        if(coklat.isSelected()){
            hargaTopping = 1000;
        }else if(stroberi.isSelected()){
            hargaTopping = 2000;
        }else if(bluberi.isSelected()){
            hargaTopping = 2000;
        }else if(keju.isSelected()){
            hargaTopping = 3000;
        }else if(kacang.isSelected()){
            hargaTopping = 2000;
        }else if(tanpa.isSelected()){
            hargaTopping = 0;
        }
        
        double totalHarga = (hargaRoti + hargaTopping) * BanyakPesanan;
        if (totalHarga > 100000) {
        totalHarga *= 0.95;
}

       rhasil.setText(String.format("Rp %.2f", totalHarga));
       rhasil.setEditable(false);

        
         if (isi < 1) {
            JOptionPane.showMessageDialog(this, "Masukkan angka yang valid!");
            return;
        }
    }//GEN-LAST:event_btnhActionPerformed

    private void rcashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rcashActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rcashActionPerformed

    private void coklatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coklatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coklatActionPerformed

    private void kejuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kejuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kejuActionPerformed

    private void croiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_croiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_croiActionPerformed

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        // TODO add your handling code here:
          BanyakPesanan++;
          jumlah.setText(String.valueOf(BanyakPesanan));
    }//GEN-LAST:event_tambahActionPerformed

    private void btnkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkActionPerformed
        // TODO add your handling code here:
          if (BanyakPesanan > 0){  
            BanyakPesanan--;
            jumlah.setText(String.valueOf(BanyakPesanan));
        }
    }//GEN-LAST:event_btnkActionPerformed

    private void rresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rresetActionPerformed
        // TODO add your handling code here:
        Roti.clearSelection();
        Topping.clearSelection();
        jumlah.setText("0");
        rcash.setText("");
        rback.setText("");
        rhasil.setText("");

    }//GEN-LAST:event_rresetActionPerformed

    private void bluberiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bluberiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bluberiActionPerformed

    private void rhasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rhasilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rhasilActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(prak2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(prak2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(prak2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(prak2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new prak2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Roti;
    private javax.swing.ButtonGroup Topping;
    private javax.swing.JRadioButton bakar;
    private javax.swing.JRadioButton bantal;
    private javax.swing.JRadioButton bluberi;
    private javax.swing.JRadioButton brio;
    private javax.swing.JButton btnh;
    private javax.swing.JButton btnk;
    private javax.swing.JRadioButton coklat;
    private javax.swing.JRadioButton croi;
    private javax.swing.JRadioButton donat;
    private javax.swing.JRadioButton goreng;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField jumlah;
    private javax.swing.JRadioButton kacang;
    private javax.swing.JRadioButton keju;
    private javax.swing.JRadioButton manis;
    private javax.swing.JRadioButton pisang;
    private javax.swing.JTextField rback;
    private javax.swing.JTextField rcash;
    private javax.swing.JTextField rhasil;
    private javax.swing.JPanel rhitung;
    private javax.swing.JButton rreset;
    private javax.swing.JRadioButton stroberi;
    private javax.swing.JButton tambah;
    private javax.swing.JRadioButton tanpa;
    private javax.swing.JRadioButton tawar;
    // End of variables declaration//GEN-END:variables
}
