/*import javax.swing.JOptionPane;
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import javax.swing.JOptionPane;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
/**
 *
 * @author Asus
 */
public class Prakss3 extends javax.swing.JFrame {

    /**
     * Creates new form Prakss3
     */
    public Prakss3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        Pilihanobat = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        buton1 = new javax.swing.JButton();
        entrostop = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        bodrex = new javax.swing.JRadioButton();
        samobyon = new javax.swing.JRadioButton();
        promag = new javax.swing.JRadioButton();
        tolakangin = new javax.swing.JRadioButton();
        insto = new javax.swing.JRadioButton();
        panadol = new javax.swing.JRadioButton();
        dulkolax = new javax.swing.JRadioButton();
        komix = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        gejalapenyakit = new javax.swing.JComboBox<>();
        betadin = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Downloads\\Foto Buat GUI\\Blogger-removebg-preview.png")); // NOI18N
        jPanel1.add(jLabel1);

        jLabel2.setFont(new java.awt.Font("STZhongsong", 1, 14)); // NOI18N
        jLabel2.setText("Apotek Mini Ngawi Selatan");
        jPanel1.add(jLabel2);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Downloads\\Foto Buat GUI\\Young_Doctor_stock_vector__Illustration_of_friendly__physician_-_65642392-removebg-preview.png")); // NOI18N
        jPanel1.add(jLabel3);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jButton2.setBackground(new java.awt.Color(255, 102, 102));
        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);

        jButton3.setBackground(new java.awt.Color(255, 204, 255));
        jButton3.setText("Keluar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);

        jButton1.setBackground(new java.awt.Color(153, 204, 255));
        jButton1.setText("Pilih Obat");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Downloads\\Foto Buat GUI\\download__5_-removebg-preview.png")); // NOI18N
        jPanel3.add(jLabel4, new java.awt.GridBagConstraints());

        buton1.setBackground(new java.awt.Color(153, 153, 255));
        buton1.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        buton1.setText("Detail");
        buton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel3.add(buton1, gridBagConstraints);

        Pilihanobat.add(entrostop);
        entrostop.setText("Entrostop");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel3.add(entrostop, gridBagConstraints);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Downloads\\Foto Buat GUI\\id-11134207-7r98y-lprn4qla2arq64-removebg-preview.png")); // NOI18N
        jPanel3.add(jLabel5, new java.awt.GridBagConstraints());

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Downloads\\Foto Buat GUI\\download__7_-removebg-preview.png")); // NOI18N
        jPanel3.add(jLabel6, new java.awt.GridBagConstraints());

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Downloads\\Foto Buat GUI\\download__8_-removebg-preview.png")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        jPanel3.add(jLabel7, gridBagConstraints);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Downloads\\Foto Buat GUI\\download__9_-removebg-preview.png")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        jPanel3.add(jLabel8, gridBagConstraints);

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Downloads\\instokecil.png")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        jPanel3.add(jLabel9, gridBagConstraints);

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Downloads\\Foto Buat GUI\\download__10_-removebg-preview.png")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        jPanel3.add(jLabel10, gridBagConstraints);

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Downloads\\Foto Buat GUI\\download__6_-removebg-preview.png")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        jPanel3.add(jLabel11, gridBagConstraints);

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Downloads\\komikkecil.png")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        jPanel3.add(jLabel12, gridBagConstraints);

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Downloads\\Foto Buat GUI\\meme-removebg-preview.png")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        jPanel3.add(jLabel13, gridBagConstraints);

        jButton4.setBackground(new java.awt.Color(153, 153, 255));
        jButton4.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jButton4.setText("Detail");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        jPanel3.add(jButton4, gridBagConstraints);

        jButton5.setBackground(new java.awt.Color(153, 153, 255));
        jButton5.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jButton5.setText("Detail");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        jPanel3.add(jButton5, gridBagConstraints);

        jButton6.setBackground(new java.awt.Color(153, 153, 255));
        jButton6.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jButton6.setText("Detail");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        jPanel3.add(jButton6, gridBagConstraints);

        jButton7.setBackground(new java.awt.Color(153, 153, 255));
        jButton7.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jButton7.setText("Detail");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        jPanel3.add(jButton7, gridBagConstraints);

        jButton8.setBackground(new java.awt.Color(153, 153, 255));
        jButton8.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jButton8.setText("Detail");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        jPanel3.add(jButton8, gridBagConstraints);

        jButton9.setBackground(new java.awt.Color(153, 153, 255));
        jButton9.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jButton9.setText("Detail");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        jPanel3.add(jButton9, gridBagConstraints);

        jButton10.setBackground(new java.awt.Color(153, 153, 255));
        jButton10.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jButton10.setText("Detail");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        jPanel3.add(jButton10, gridBagConstraints);

        jButton11.setBackground(new java.awt.Color(153, 153, 255));
        jButton11.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jButton11.setText("Detail");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        jPanel3.add(jButton11, gridBagConstraints);

        jButton12.setBackground(new java.awt.Color(153, 153, 255));
        jButton12.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jButton12.setText("Detail");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        jPanel3.add(jButton12, gridBagConstraints);

        Pilihanobat.add(bodrex);
        bodrex.setText("Bodrex");
        bodrex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bodrexActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        jPanel3.add(bodrex, gridBagConstraints);

        Pilihanobat.add(samobyon);
        samobyon.setText("Samobyon");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        jPanel3.add(samobyon, gridBagConstraints);

        Pilihanobat.add(promag);
        promag.setText("Promaag");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        jPanel3.add(promag, gridBagConstraints);

        Pilihanobat.add(tolakangin);
        tolakangin.setText("Tolak Angin");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        jPanel3.add(tolakangin, gridBagConstraints);

        Pilihanobat.add(insto);
        insto.setText("insto");
        insto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        jPanel3.add(insto, gridBagConstraints);

        Pilihanobat.add(panadol);
        panadol.setText("Panadol");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        jPanel3.add(panadol, gridBagConstraints);

        Pilihanobat.add(dulkolax);
        dulkolax.setText("dulkolax");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        jPanel3.add(dulkolax, gridBagConstraints);

        Pilihanobat.add(komix);
        komix.setText("komix");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        jPanel3.add(komix, gridBagConstraints);

        jLabel14.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel14.setText("Gejala :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel3.add(jLabel14, gridBagConstraints);

        gejalapenyakit.setBackground(new java.awt.Color(204, 204, 255));
        gejalapenyakit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----Pilih Gejala Penyakit----", "Diare", "Sakit Kepala", "Kurang Darah", "Maag", "Masuk Angin", "Sakit Mata", "Demam", "Batuk Berdahak", "Sembelit", "Infeksi" }));
        gejalapenyakit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gejalapenyakitActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel3.add(gejalapenyakit, gridBagConstraints);

        Pilihanobat.add(betadin);
        betadin.setText("betadin");
        betadin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                betadinActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 11;
        jPanel3.add(betadin, gridBagConstraints);

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton1ActionPerformed
        // TODO add your handling code here:
          String detailObat = "Nama: Entrostop\nKegunaan: Mengatasi Diare \nDosis: 2 tablet setiap buang air besar";
    JOptionPane.showMessageDialog(this, detailObat, "Detail Obat", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_buton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
          String detailObat = "Nama: Bodrex\nKegunaan: Mengatasi sakit kepala dan demam\nDosis: 1 tablet 3 kali sehari";
    JOptionPane.showMessageDialog(this, detailObat, "Detail Obat", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
          String detailObat = "Nama: Samobyon\nKegunaan: Menambah darah untuk penderita darah rendah\nDosis: 1 tablet 1 kali sehari";
    JOptionPane.showMessageDialog(this, detailObat, "Detail Obat", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
          String detailObat = "Nama: Promaag\nKegunaan: Mengatasi Maag\nDosis: 1 sachet 2 kali sehari";
    JOptionPane.showMessageDialog(this, detailObat, "Detail Obat", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
          String detailObat = "Nama: Tolak Angin\nKegunaan: Mengatasi Masuk Angin \nDosis: 1 sacher kali sehari";
    JOptionPane.showMessageDialog(this, detailObat, "Detail Obat", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
          String detailObat = "Nama: Insto \nKegunaan: Mengatasi sakit mata / mata merah\nDosis: 1 tetes 3 kali sejhari ";
    JOptionPane.showMessageDialog(this, detailObat, "Detail Obat", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
          String detailObat = "Nama: Panadol \nKegunaan: Mengurangi sakit kepala sebelah atau migrain \nDosis: 1 tablet 3 kali sehari";
    JOptionPane.showMessageDialog(this, detailObat, "Detail Obat", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
          String detailObat = "Nama: dulkolax\nKegunaan: Mengatasi Sembelit \nDosis: 1 - 2 tablet sehari";
    JOptionPane.showMessageDialog(this, detailObat, "Detail Obat", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
          String detailObat = "Nama: Komix\nKegunaan: Meredakan batuk biasa hingga berdahak\nDosis: 1 tablet 2 kali sehari";
    JOptionPane.showMessageDialog(this, detailObat, "Detail Obat", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
          String detailObat = "Nama: Betadin\nKegunaan: Mengatasi infeksi pada luka\nDosis: 1- 3 kali oles sehari";
    JOptionPane.showMessageDialog(this, detailObat, "Detail Obat", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void instoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_instoActionPerformed

    private void gejalapenyakitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gejalapenyakitActionPerformed
        // TODO add your handling code here:
        String gejala = (String) gejalapenyakit.getSelectedItem();
    
        if ("Diare".equals(gejala)) {        
        JOptionPane.showMessageDialog(this, "Rekomendasi obat : Entrostop\nSilahkan Pilih Di Menu ini", "Obat Rekomendasi", JOptionPane.INFORMATION_MESSAGE);
        entrostop.setSelected(true);
        } else if ("Sakit Kepala".equals(gejala)) {
        JOptionPane.showMessageDialog(this, "Rekomendasi obat : Bodrex\nSilahkan Pilih Di Menu ini", "Obat Rekomendasi", JOptionPane.INFORMATION_MESSAGE);
        bodrex.setSelected(true);
        } else if ("Kurang Darah".equals(gejala)) {
        JOptionPane.showMessageDialog(this, "Rekomendasi obat : Samobyon\nSilahkan Pilih Di Menu ini ", "Obat Rekomendasi", JOptionPane.INFORMATION_MESSAGE);
        samobyon.setSelected(true);
        } else if ("Maag".equals(gejala)) {
        JOptionPane.showMessageDialog(this, "Rekomendasi obat :  Promaag\nSilahkan Pilih Di Menu ini ", "Obat Rekomendasi", JOptionPane.INFORMATION_MESSAGE);
        promag.setSelected(true);
        } else if ("Masuk Angin".equals(gejala)) {
        JOptionPane.showMessageDialog(this, "Rekomendasi obat :  tolakangin\nSilahkan Pilih Di Menu Bawah!", "Obat Rekomendasi", JOptionPane.INFORMATION_MESSAGE);
        tolakangin.setSelected(true);
        } else if ("Sakit Mata".equals(gejala)) {
        JOptionPane.showMessageDialog(this, "Rekomendasi obat :  insto\nSilahkan Pilih Di Menu Bawah!", "Obat Rekomendasi", JOptionPane.INFORMATION_MESSAGE);
        insto.setSelected(true);
        } else if ("Demam".equals(gejala)) {
        JOptionPane.showMessageDialog(this, "Rekomendasi obat :  panadol\nSilahkan Pilih Di Menu Bawah!", "Obat Rekomendasi", JOptionPane.INFORMATION_MESSAGE);
        panadol.setSelected(true);
        } else if ("batuk berdahak".equals(gejala)) {
        JOptionPane.showMessageDialog(this, "Rekomendasi obat :  komix\nSilahkan Pilih Di Menu Bawah!", "Obat Rekomendasi", JOptionPane.INFORMATION_MESSAGE);
        komix.setSelected(true);
        } else if ("Sembelit".equals(gejala)) {
        JOptionPane.showMessageDialog(this, "Rekomendasi obat :  dulkolax\nSilahkan Pilih Di Menu Bawah!", "Obat Rekomendasi", JOptionPane.INFORMATION_MESSAGE);
        dulkolax.setSelected(true);
        } else if ("Infeksi".equals(gejala)) {
        JOptionPane.showMessageDialog(this, "Rekomendasi obat :  betadin\nSilahkan Pilih Di Menu Bawah!", "Obat Rekomendasi", JOptionPane.INFORMATION_MESSAGE);
        betadin.setSelected(true);
        }
    
    }//GEN-LAST:event_gejalapenyakitActionPerformed

    private void betadinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_betadinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_betadinActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        gejalapenyakit.setSelectedIndex(0);
        Pilihanobat.clearSelection();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int option = JOptionPane.showConfirmDialog(this,"ingin keluar?","Konfirmasi",JOptionPane.YES_NO_OPTION);

        if (option == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(this,"Terimakasih Telah Mencoba Layanan Kami","Pesan",JOptionPane.INFORMATION_MESSAGE);
            System.exit(0);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int hargaentrostop = 12000;
        int hargabodrex = 20000;
        int hargasamobyon = 13000;
        int hargapromaag = 23000;
        int hargatolakangin = 11000;
        int hargainsto = 19000;
        int hargapanadol = 15000;
        int hargakomix = 14000;
        int hargadulkolax = 27000;
        int hargabetadin = 15500;
        
        
         if (entrostop.isSelected()) {
            JOptionPane.showMessageDialog(this, 
            "Anda memilih: entrostop \nHarga: " + hargaentrostop + " IDR" + "\nSilahkan bawa Struk ini ke kasir untuk melakukan Pembayaran", 
            "Struk Pembelian", JOptionPane.INFORMATION_MESSAGE);
        } else if (bodrex.isSelected()) {
            JOptionPane.showMessageDialog(this, 
            "Anda memilih: bodrex \nHarga: " + hargabodrex + " IDR" + "\nSilahkan bawa Struk ini ke kasir untuk melakukan Pembayaran", 
            "Struk Pembelian", JOptionPane.INFORMATION_MESSAGE);
        } else if (samobyon.isSelected()) {
            JOptionPane.showMessageDialog(this, 
            "Anda memilih: Samobyon \nHarga: " + hargasamobyon + " IDR" + "\nSilahkan bawa Struk ini ke kasir untuk melakukan Pembayaran", 
            "Struk Pembelian", JOptionPane.INFORMATION_MESSAGE);
        } else if (promag.isSelected()) {
            JOptionPane.showMessageDialog(this, 
            "Anda memilih: Promaag \nHarga: " + hargapromaag + " IDR" + "\nSilahkan bawa Struk ini ke kasir untuk melakukan Pembayaran", 
            "Struk Pembelian", JOptionPane.INFORMATION_MESSAGE);
        } else if (tolakangin.isSelected()) {
            JOptionPane.showMessageDialog(this, 
            "Anda memilih: tolak angin \nHarga: " + hargatolakangin + " IDR" + "\nSilahkan bawa Struk ini ke kasir untuk melakukan Pembayaran", 
            "Struk Pembelian", JOptionPane.INFORMATION_MESSAGE);
        } else if (insto.isSelected()) {
            JOptionPane.showMessageDialog(this, 
            "Anda memilih: Napacin \nHarga: " + hargainsto + " IDR" + "\nSilahkan bawa Struk ini ke kasir untuk melakukan Pembayaran", 
            "Struk Pembelian", JOptionPane.INFORMATION_MESSAGE);
        } else if (panadol.isSelected()) {
            JOptionPane.showMessageDialog(this, 
            "Anda memilih: Panadol \nHarga: " + hargapanadol + " IDR" + "\nSilahkan bawa Struk ini ke kasir untuk melakukan Pembayaran", 
            "Struk Pembelian", JOptionPane.INFORMATION_MESSAGE);
        } else if (komix.isSelected()) {
            JOptionPane.showMessageDialog(this, 
            "Anda memilih: Komix \nHarga: " + hargakomix + " IDR" + "\nSilahkan bawa Struk ini ke kasir untuk melakukan Pembayaran", 
            "Struk Pembelian", JOptionPane.INFORMATION_MESSAGE);
        } else if (dulkolax.isSelected()) {
            JOptionPane.showMessageDialog(this, 
            "Anda memilih: dulkolax\nHarga: " + hargadulkolax + " IDR" + "\nSilahkan bawa Struk ini ke kasir untuk melakukan Pembayaran", 
            "Struk Pembelian", JOptionPane.INFORMATION_MESSAGE);
        } else if (betadin.isSelected()) {
            JOptionPane.showMessageDialog(this, 
            "Anda memilih: betadin\nHarga: " + hargabetadin + " IDR" + "\nSilahkan bawa Struk ini ke kasir untuk melakukan  Pembayaran", 
            "Struk Pembelian", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Silakan pilih obat yang tersedia ", "Struk Pembelian",JOptionPane.WARNING_MESSAGE);
        }
                    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bodrexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bodrexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bodrexActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prakss3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prakss3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prakss3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prakss3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Prakss3().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Pilihanobat;
    private javax.swing.JRadioButton betadin;
    private javax.swing.JRadioButton bodrex;
    private javax.swing.JButton buton1;
    private javax.swing.JRadioButton dulkolax;
    private javax.swing.JRadioButton entrostop;
    private javax.swing.JComboBox<String> gejalapenyakit;
    private javax.swing.JRadioButton insto;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton komix;
    private javax.swing.JRadioButton panadol;
    private javax.swing.JRadioButton promag;
    private javax.swing.JRadioButton samobyon;
    private javax.swing.JRadioButton tolakangin;
    // End of variables declaration//GEN-END:variables
}
